// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp5dMZIIBrO3_GhHxOakivuKCesZGv_o8',
    appId: '1:167501484195:android:6de53886c14225f036af16',
    messagingSenderId: '167501484195',
    projectId: 'restaurant-b278d',
    storageBucket: 'restaurant-b278d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2MFrINQVQxAztmeh_zB94V_WqBI40NR8',
    appId: '1:167501484195:ios:27c0f4d585868a2c36af16',
    messagingSenderId: '167501484195',
    projectId: 'restaurant-b278d',
    storageBucket: 'restaurant-b278d.firebasestorage.app',
    iosBundleId: 'com.example.restaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFMwVx6Uaxh_LKlySzrLyvp5t5wkMnNu8',
    appId: '1:167501484195:web:862a87089612b19536af16',
    messagingSenderId: '167501484195',
    projectId: 'restaurant-b278d',
    authDomain: 'restaurant-b278d.firebaseapp.com',
    storageBucket: 'restaurant-b278d.firebasestorage.app',
    measurementId: 'G-FEYGS5393C',
  );
}
